server:
  port: 8085
  servlet:
    context-path: /api/v1

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  swagger-ui:
    path: ${server.servlet.context-path}/swagger-ui/index.html